In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
# Load the data
file_path = '../data/sales_data_sample.csv'
df = pd.read_csv(file_path, encoding='Windows-1252')

# Preview first few rows
df.head()

# Shape of data
print("Dataset shape:", df.shape)

# Summary of data
df.info()

# Checking for missing values
df.isnull().sum()

# Checking and removing duplicates
print("Duplicate rows:", df.duplicated().sum())
df = df.drop_duplicates()

df['ORDERDATE'] = pd.to_datetime(df['ORDERDATE'], errors='coerce')
df = df.dropna(subset=['ORDERDATE'])

Dataset shape: (2823, 25)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   object
 6   STATUS            2823 non-null   object
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   object
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   object
 13  CUSTOMERNAME      2823 non-null   object
 14  PHONE             2823 non-null   object
 15  ADDRESSLINE1      2823 non-null   object
 16  ADDRESSLINE2      302 non-null    object
 17  CITY              2823 non-null   object
 18  STATE             1337 non-null   object
 19  POSTALCODE        2747 non-null   object
 20  COUNTRY           2823 non-null   object
 21  TERRITORY         1749 non-null   object
 22  CONTACTLASTNAME   2823 non-null   object
 23  CONTACTFIRSTNAME  2823 non-null   object
 24  DEALSIZE          2823 non-null   object
dtypes: float64(2), int64(7), object(16)
memory usage: 551.5+ KB
Duplicate rows: 0

In [16]:
scaler = MinMaxScaler()

num_cols = ['SALES', 'QUANTITYORDERED', 'PRICEEACH']

df[num_cols] = scaler.fit_transform(df[num_cols])
#Encoding categorical variables
cat_cols = ['COUNTRY', 'CUSTOMERNAME', 'PRODUCTLINE', 'DEALSIZE']

label_encoders = {}

for col in cat_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

df.to_csv('../data/cleaned_sales_data.csv', index=False)
print("Preprocessed data saved!")
# Checking the final data
print(df.head())
df.describe()
df.info()

Preprocessed data saved!
   ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER     SALES  \
0        10107         0.263736   0.941193                2  0.175644
1        10121         0.307692   0.744940                5  0.167916
2        10134         0.384615   0.928063                2  0.250150
3        10145         0.428571   0.771061                6  0.240030
4        10159         0.472527   1.000000               14  0.347273

   ORDERDATE   STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  \
0 2003-02-24  Shipped       1         2     2003  ...
1 2003-05-07  Shipped       2         5     2003  ...
2 2003-07-01  Shipped       3         7     2003  ...
3 2003-08-25  Shipped       3         8     2003  ...
4 2003-10-10  Shipped       4        10     2003  ...

                    ADDRESSLINE1  ADDRESSLINE2           CITY  STATE  \
0        897 Long Airport Avenue           NaN            NYC     NY
1             59 rue de l'Abbaye           NaN          Reims    NaN
2  27 rue du Colonel Pierre Avia           NaN          Paris    NaN
3             78934 Hillside Dr.           NaN       Pasadena     CA
4                7734 Strong St.           NaN  San Francisco     CA

  POSTALCODE COUNTRY TERRITORY CONTACTLASTNAME CONTACTFIRSTNAME DEALSIZE
0      10022      18       NaN              Yu             Kwai        2
1      51100       6      EMEA         Henriot             Paul        2
2      75508       6      EMEA        Da Cunha           Daniel        1
3      90003      18       NaN           Young            Julie        1
4        NaN      18       NaN           Brown            Julie        1

[5 rows x 25 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   float64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   datetime64[ns]
 6   STATUS            2823 non-null   object
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   int64
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   object
 13  CUSTOMERNAME      2823 non-null   int64
 14  PHONE             2823 non-null   object
 15  ADDRESSLINE1      2823 non-null   object
 16  ADDRESSLINE2      302 non-null    object
 17  CITY              2823 non-null   object
 18  STATE             1337 non-null   object
 19  POSTALCODE        2747 non-null   object
 20  COUNTRY           2823 non-null   int64
 21  TERRITORY         1749 non-null   object
 22  CONTACTLASTNAME   2823 non-null   object
 23  CONTACTFIRSTNAME  2823 non-null   object
 24  DEALSIZE          2823 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(10), object(11)
memory usage: 551.5+ KB